REM ARMAZENANDO O CAMINHO DO BAT NA VARIIÁVEL PATH
@SET "curpath=%~dp0"

REM REMOVE A ÚLTIMA BARRA DO PAT
@IF %curpath:~-1%==\ SET curpath=%curpath:~0,-1%

REM SE HOUVER ERRO FINALIA
@IF ERRORLEVEL 1 GOTO end

REM ALTERANDO PARA O DIRETORIO ONDE ESTÁ O EXECUTÁVEL DO SpecRun
@cd SpecRun\

REM SETANDO UM PROFILE DE EXECUÇÃO
@SET profile=%1

REM CASO NÃO TENHA UM DEFINIDO UTILIZA O PADRÃO
@IF "%profile%" == "" SET profile=Default

REM EXECUÇÃO DO SpecRun COM UM PROFILE E O DIRETORIO ONDE ESTÁ A DLL DO PROJETO DE TESTES 
SpecRun.exe run %profile%.srprofile "/baseFolder: %curpath%" 

:end

@POPD
